import { api, API_URL, getToken } from "@/lib/api";

const STARTER_HTML = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{{title}}</title>
    <style>
      body { font-family: Inter, system-ui, -apple-system, sans-serif; color: #111; padding: 48px; }
      h1 { margin: 0 0 8px; font-size: 28px; }
      .muted { color: #666; font-size: 14px; }
      .card { margin-top: 24px; padding: 16px 20px; border: 1px solid #e5e7eb; border-radius: 8px; }
    </style>
  </head>
  <body>
    <h1>Hello, {{name}}</h1>
    <div class="muted">Generated by Formly</div>
    <div class="card">
      <p>This is a starter HTML template. Use double curlies to add placeholders,
      for example <code>{{customer.email}}</code>.</p>
    </div>
  </body>
</html>
`;

// Creates a new HTML template: uploads a starter file, marks it complete so the
// detector creates the template, moves it into the current folder, and returns
// the created templateId.
export async function createHtmlTemplate(opts: {
  name: string;
  content?: string;
  folderId?: string;
}): Promise<{ fileId: string; templateId: string }> {
  const filename = opts.name.endsWith(".html") ? opts.name : `${opts.name}.html`;
  const body = opts.content ?? STARTER_HTML;

  const { fileId, uploadUrl } = await api<{
    fileId: string;
    uploadUrl: string;
  }>("/v1/files/upload-url", {
    method: "POST",
    body: JSON.stringify({ name: filename, mime: "text/html" }),
  });

  // Direct PUT to MinIO pre-signed URL.
  const putRes = await fetch(uploadUrl, {
    method: "PUT",
    headers: { "Content-Type": "text/html" },
    body,
  });
  if (!putRes.ok) throw new Error(`upload failed: ${putRes.status}`);

  const complete = await api<{ templateId?: string }>(
    `/v1/files/${fileId}/complete`,
    { method: "POST" }
  );
  if (!complete.templateId) {
    throw new Error("template was not created");
  }

  if (opts.folderId) {
    await api(`/v1/files/${fileId}`, {
      method: "PATCH",
      body: JSON.stringify({ folderId: opts.folderId }),
    });
  }

  return { fileId, templateId: complete.templateId };
}

// Reference to keep API_URL/getToken imported for debugging even when unused.
void API_URL;
void getToken;
