// Package aidetect proposes form-field placements for a template's
// backing PDF so the static designer can offer a one-click
// "Auto-detect fields" workflow instead of requiring the author to
// drag every widget manually.
//
// # Detection cascade
//
// The package layers three strategies behind one response shape:
//
//  1. AcroForm — deterministic. If the PDF has a real /AcroForm dict,
//     every widget annotation already carries a field name + bounding
//     rect, so we map those straight to proposed static-mode widgets.
//     Zero AI calls, zero hallucination risk, instant — but only
//     works on PDFs generated by software (Acrobat, Word,
//     LibreOffice, …).
//
//  2. Heuristic — runs the PaddleOCR sidecar's /layout/pdf endpoint
//     and applies pattern rules in internal/aidetect/heuristic to
//     infer text/checkbox/radio/signature widgets from the OCR'd
//     text + bounding boxes. Works on scanned and flattened PDFs.
//     No AI; rules-based and pure-function over the layout output.
//
//  3. Vision-LLM (Phase 4, not yet wired) — page rasters → vision
//     model with structured-output schema for field proposals.
//     Gated by ai.Client.Capabilities().Vision so it's automatically
//     disabled on operators who haven't configured a vision model.
//
// The handler runs them as a stop-at-first-non-empty cascade by
// default. Callers who want a specific tier pass ?strategy=acroform
// or ?strategy=heuristic.
//
// Important: this endpoint is read-only. It NEVER mutates the
// template — the client receives a list of proposals, the user picks
// which to accept (and edits names), and only then does the existing
// PUT /v1/templates/{id}/widgets persist them. That keeps the AI
// surface side-effect-free and lets us layer additional detection
// strategies behind the same response shape without changing the
// apply path.
package aidetect

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"regexp"
	"strings"

	"github.com/docforge/api/internal/ai"
	"github.com/docforge/api/internal/aidetect/heuristic"
	"github.com/docforge/api/internal/aidetect/visionllm"
	"github.com/docforge/api/internal/auth"
	"github.com/docforge/api/internal/generate/acroform"
	"github.com/docforge/api/internal/ocr"
	"github.com/docforge/api/internal/sharing"
	"github.com/docforge/api/internal/storage"
	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Handler struct {
	DB      *pgxpool.Pool
	Storage *storage.Client

	// OCR is the layout-extracting client used by the heuristic tier
	// AND the rasterizing client used by the vision-LLM tier. When
	// OCR.Enabled is false both tier-2 and tier-3 are silently skipped
	// (the operator opted out of the sidecar) and the response surfaces
	// a hint instead of a hard error so the AcroForm path keeps
	// working unchanged.
	OCR ocr.Config

	// AI is the vision-capable model client used by the third tier.
	// May be the Disabled provider — Detect() gates on
	// AI.Capabilities().Vision before opening any rasters, so a text-
	// only AI configuration short-circuits cleanly.
	AI ai.Client
}

func New(db *pgxpool.Pool, s *storage.Client, ocrCfg ocr.Config, aiClient ai.Client) *Handler {
	return &Handler{DB: db, Storage: s, OCR: ocrCfg, AI: aiClient}
}

// Proposal is one auto-detected widget the client may choose to
// accept. Geometry is in PDF user-space (origin bottom-left, units =
// points) so it drops straight into the static designer without
// coordinate translation. PageW/PageH ride along so the frontend can
// scale the overlay before the user has rendered the corresponding
// page (PDF.js gives page dims at render time, not earlier).
type Proposal struct {
	Type     string                 `json:"type"`
	Page     int                    `json:"page"`
	X        float64                `json:"x"`
	Y        float64                `json:"y"`
	W        float64                `json:"w"`
	H        float64                `json:"h"`
	DataKey  string                 `json:"dataKey"`
	Label    string                 `json:"label,omitempty"`    // human-readable hint (PDF field name)
	PageW    float64                `json:"pageW,omitempty"`
	PageH    float64                `json:"pageH,omitempty"`
	Props    map[string]interface{} `json:"props,omitempty"`
	// Source attribution per-proposal so future passes (vision-AI,
	// heuristic) can mark how confident they are. AcroForm extraction
	// is always a deterministic match, so we just stamp "acroform".
	Source     string  `json:"source"`
	Confidence float64 `json:"confidence"` // 0..1; AcroForm always 1.0
}

type detectResp struct {
	// Source is the strategy that actually produced the proposals —
	// "acroform" / "heuristic" / "vision" / "none". The frontend
	// renders different colour-coded chips per source.
	Source    string     `json:"source"`
	Count     int        `json:"count"`
	Proposals []Proposal `json:"proposals"`
	// Message is a human-readable hint when count==0, telling the user
	// why nothing was detected and what to try next. Surfaced by the
	// modal as the empty-state copy.
	Message string `json:"message,omitempty"`
}

// MarshalJSON ensures Proposals is always an array on the wire, never
// null. Go's encoding/json would otherwise serialize a nil slice as
// `null` — every cascade path that returns "no fields" currently
// constructs the response with a nil slice, and the frontend's
// .forEach / .map calls then crash with TypeError. Normalising here
// (rather than fixing each construction site) keeps future code paths
// safe by default.
func (d detectResp) MarshalJSON() ([]byte, error) {
	type alias detectResp // alias breaks the recursion into MarshalJSON
	out := alias(d)
	if out.Proposals == nil {
		out.Proposals = []Proposal{}
	}
	return json.Marshal(out)
}

// DetectFields: POST /v1/templates/{id}/ai/detect-fields[?strategy=auto|acroform|heuristic|vision]
//
// Runs the field-detection cascade described in the package doc and
// returns a list of proposed static widgets the designer can show in
// a "review and accept" modal. No DB writes.
//
// Strategy selection:
//
//   - auto (default): AcroForm → heuristic → vision-LLM, stops at
//     first non-empty tier
//   - acroform: only the deterministic /AcroForm path
//   - heuristic: only the OCR-based pattern detector
//   - vision: only the vision-LLM tier (requires AI_VISION_MODEL set
//     OR an Anthropic provider, which has Vision=true unconditionally)
//
// Auth: same edit-permission gate as the rest of the template
// designer surface (viewers can read but mustn't trigger an action
// that nudges the author toward writing changes).
func (h *Handler) DetectFields(w http.ResponseWriter, r *http.Request) {
	c := r.Context().Value(auth.UserCtxKey).(*auth.Claims)
	id := chi.URLParam(r, "id")
	strategy := parseStrategy(r.URL.Query().Get("strategy"))

	var mode, fileID, storageKey, mime string
	err := h.DB.QueryRow(r.Context(),
		`SELECT t.mode, t.file_id, f.storage_key, COALESCE(f.mime,'')
		 FROM templates t JOIN files f ON f.id=t.file_id
		 WHERE t.id=$1 AND t.org_id=$2`, id, c.OrgID,
	).Scan(&mode, &fileID, &storageKey, &mime)
	if err != nil {
		writeErr(w, 404, "not_found", "template not found")
		return
	}
	if ok, err := sharing.CanEditFile(r.Context(), h.DB, c, fileID); err != nil {
		writeErr(w, 500, "db_error", err.Error())
		return
	} else if !ok {
		writeErr(w, 403, "forbidden", "you don't have edit access to this template")
		return
	}
	// AcroForm + heuristic both target PDF-backed templates (static /
	// acroform modes). HTML / markdown / doc / image have no widget
	// geometry to detect; reject up-front so the UI doesn't silently
	// report "no fields found" for a misroute.
	if mode != "static" && mode != "acroform" {
		writeErr(w, 400, "wrong_mode",
			"auto-detect only supports PDF-backed templates (static / acroform)")
		return
	}
	if !looksLikePDF(mime, storageKey) {
		writeErr(w, 400, "wrong_kind",
			"auto-detect requires a PDF source")
		return
	}

	pdfBytes, err := h.Storage.GetBytes(r.Context(), storageKey)
	if err != nil {
		writeErr(w, 500, "storage", err.Error())
		return
	}

	// Tier 1 — AcroForm. Always tried in auto/acroform modes; skipped
	// when the caller has pinned heuristic or vision (they want the
	// later tier's output regardless of what AcroForm would produce).
	var acroProposals []Proposal
	var acroErr error
	if strategy == StrategyAuto || strategy == StrategyAcroForm {
		acroProposals, acroErr = h.acroformProposals(pdfBytes)
	}

	// Auto-mode short-circuit: if AcroForm yielded anything, ship it.
	// The heuristic tier is more useful as a fallback than as an
	// addition (it would re-detect the same fields with lower
	// confidence and make the modal noisy).
	if strategy == StrategyAuto && len(acroProposals) > 0 {
		writeJSON(w, 200, detectResp{
			Source:    "acroform",
			Count:     len(acroProposals),
			Proposals: acroProposals,
		})
		return
	}

	// Caller pinned acroform: report exactly what AcroForm produced
	// (including the empty case with a helpful message).
	if strategy == StrategyAcroForm {
		resp := detectResp{Source: "acroform", Count: len(acroProposals), Proposals: acroProposals}
		if len(acroProposals) == 0 {
			resp.Source = "none"
			if acroErr != nil {
				resp.Message = "Couldn't read AcroForm fields from this PDF (" + acroErr.Error() + "). Try ?strategy=heuristic to use OCR-based detection."
			} else {
				resp.Message = "No AcroForm fields detected. Try ?strategy=heuristic to use OCR-based detection on scanned/flat forms."
			}
		}
		writeJSON(w, 200, resp)
		return
	}

	// Caller pinned vision: skip heuristic entirely, run only the
	// vision-LLM tier. This is the "I trust the model more than the
	// OCR rules" path.
	if strategy == StrategyVision {
		resp := h.runVisionTier(r.Context(), pdfBytes, len(acroProposals))
		writeJSON(w, 200, resp)
		return
	}

	// Tier 2 — Heuristic over OCR layout. Requires OCR sidecar to be
	// enabled for the layout endpoint. If OCR is off we fall through
	// to vision (auto mode) when possible, otherwise return whatever
	// AcroForm produced.
	if !h.OCR.Enabled {
		// In auto mode with OCR off, give vision a shot before giving up.
		if strategy == StrategyAuto && h.canRunVision() {
			// We need rasters but the OCR sidecar is the rasterizer
			// too — without it we can't feed the vision model. Surface
			// a helpful message instead of silently producing nothing.
			resp := detectResp{Source: "acroform", Count: len(acroProposals), Proposals: acroProposals}
			if len(acroProposals) == 0 {
				resp.Source = "none"
				resp.Message = "OCR sidecar disabled — heuristic and vision-AI detection both require it for PDF rasterization. Set OCR_ENABLED=1 + run the paddle-ocr sidecar."
			}
			writeJSON(w, 200, resp)
			return
		}
		resp := detectResp{Source: "acroform", Count: len(acroProposals), Proposals: acroProposals}
		if len(acroProposals) == 0 {
			resp.Source = "none"
			resp.Message = "No AcroForm fields detected. Enable OCR (set OCR_ENABLED=1 + run the paddle-ocr sidecar) for scanned-form detection."
		}
		writeJSON(w, 200, resp)
		return
	}

	pages, ocrErr := h.OCR.LayoutPDF(r.Context(), pdfBytes)
	if ocrErr != nil {
		// Heuristic unavailable. Auto mode falls through to vision;
		// pinned heuristic fails closed with the OCR error.
		if strategy == StrategyAuto && h.canRunVision() {
			resp := h.runVisionTier(r.Context(), pdfBytes, len(acroProposals))
			writeJSON(w, 200, resp)
			return
		}
		resp := detectResp{Source: "acroform", Count: len(acroProposals), Proposals: acroProposals}
		if len(acroProposals) == 0 {
			resp.Source = "none"
			if errors.Is(ocrErr, ocr.ErrSidecarUnavailable) {
				resp.Message = "OCR sidecar unreachable — heuristic detection unavailable. Configure AI_VISION_MODEL (or an Anthropic key) to enable vision-AI fallback."
			} else {
				resp.Message = "OCR layout extraction failed: " + ocrErr.Error()
			}
		}
		writeJSON(w, 200, resp)
		return
	}

	heurFields := heuristic.Detect(pages)
	heurProposals := proposalsFromHeuristic(heurFields, h.OCR.DPI, len(acroProposals))

	// Pinned heuristic: ship heuristic regardless of what auto-cascade
	// would have done. Empty result still returns the heuristic tag.
	if strategy == StrategyHeuristic {
		resp := detectResp{Source: "heuristic", Count: len(heurProposals), Proposals: heurProposals}
		if len(heurProposals) == 0 {
			resp.Source = "none"
			resp.Message = "No fillable fields detected by the OCR heuristic. Try ?strategy=vision or ?strategy=merge for the vision-AI tier."
		}
		writeJSON(w, 200, resp)
		return
	}

	// Auto + Merge: when vision is available, run it in parallel with
	// the heuristic and union the two detections by spatial overlap
	// (see merge.go). This is the recall-lift path — heuristic catches
	// structural patterns (boxes, underlines, glyph checkboxes), vision
	// catches semantic ones (character grids, table cells, signature
	// lines, multi-column layouts), and the merge produces ~1.5-2x the
	// recall of either tier alone on dense banking / govt forms.
	//
	// Pinned `merge` runs even if heuristic returned a healthy result;
	// `auto` only invokes the merge when vision is actually configured
	// (otherwise it ships heuristic-only, same as the legacy cascade).
	wantMerge := strategy == StrategyMerge ||
		(strategy == StrategyAuto && h.canRunVision())
	if wantMerge && h.canRunVision() {
		// Run vision in parallel with the work we already did. The
		// heuristic call above is synchronous because it's CPU-bound
		// and fast; vision is an LLM round-trip per page (potentially
		// seconds), so we kick it off here and merge when it returns.
		// We use a buffered channel of size 1 so the goroutine never
		// blocks even if the request context is cancelled before we
		// receive — ctx cancellation propagates through visionllm.
		visionCh := make(chan visionResult, 1)
		go func(ctx context.Context, idxOffset int) {
			pages, err := h.OCR.RasterPDF(ctx, pdfBytes)
			if err != nil {
				visionCh <- visionResult{err: err}
				return
			}
			visFields, err := visionllm.Detect(ctx, h.AI, pages)
			if err != nil {
				visionCh <- visionResult{err: err}
				return
			}
			props := proposalsFromHeuristic(visFields, h.OCR.DPI, idxOffset)
			for i := range props {
				props[i].Source = "vision"
			}
			visionCh <- visionResult{proposals: props}
		}(r.Context(), len(acroProposals)+len(heurProposals))

		visRes := <-visionCh

		if visRes.err == nil && (len(visRes.proposals) > 0 || len(heurProposals) > 0) {
			merged := mergeProposals(heurProposals, visRes.proposals)
			if len(merged) > 0 {
				writeJSON(w, 200, detectResp{
					Source:    "merged",
					Count:     len(merged),
					Proposals: merged,
				})
				return
			}
		}
		// Vision failed or both empty — fall through to the
		// heuristic-only / vision-only / nothing branches below.
		// This degrades gracefully without a 5xx for vision outages.
	}

	// Auto cascade (vision unavailable or merge produced nothing):
	// ship heuristic if it has anything, otherwise try vision-only as
	// a final fallback.
	if len(heurProposals) > 0 {
		writeJSON(w, 200, detectResp{
			Source:    "heuristic",
			Count:     len(heurProposals),
			Proposals: heurProposals,
		})
		return
	}

	// Tier 3 — Vision-LLM standalone. Reached when AcroForm + heuristic
	// both produced zero AND the merge path didn't run (or returned
	// empty). Useful when heuristic blanks but vision can still see
	// fields it could have contributed to a merge.
	if h.canRunVision() {
		resp := h.runVisionTier(r.Context(), pdfBytes, len(acroProposals))
		writeJSON(w, 200, resp)
		return
	}

	// Out of options — surface the most actionable message we can.
	writeJSON(w, 200, detectResp{
		Source:  "none",
		Count:   0,
		Message: "No fillable fields detected. Configure a vision-capable AI provider (set AI_PROVIDER=anthropic with AI_API_KEY, or AI_VISION_MODEL on Ollama/vLLM) to enable the vision-AI tier for visually complex layouts. The merge cascade (?strategy=merge) needs vision to be configured.",
	})
}

// visionResult bundles the goroutine's output so the merge path can
// receive a single value over a channel instead of a (proposals, err)
// pair (channels of multiple values aren't a thing in Go).
type visionResult struct {
	proposals []Proposal
	err       error
}

// canRunVision reports whether the vision tier has any chance of
// returning fields. Both the AI client and the OCR sidecar (for
// rasterization) must be available — vision detection without the
// rasterizer would have nothing to feed the model.
func (h *Handler) canRunVision() bool {
	if h.AI == nil || !h.AI.Enabled() {
		return false
	}
	if !h.AI.Capabilities().Vision {
		return false
	}
	if !h.OCR.Enabled {
		return false
	}
	return true
}

// runVisionTier rasterizes the PDF, runs the vision-LLM detector,
// and packages the result into a detectResp. idxOffset lets the
// caller continue numbering synthetic data keys after the AcroForm
// tier's named fields.
func (h *Handler) runVisionTier(ctx context.Context, pdfBytes []byte, idxOffset int) detectResp {
	if !h.canRunVision() {
		return detectResp{
			Source:  "none",
			Message: "Vision-AI tier unavailable. Configure AI_PROVIDER=anthropic with AI_API_KEY, or set AI_VISION_MODEL on Ollama/vLLM. The OCR sidecar must also be running (it rasterizes the PDF for the model).",
		}
	}
	pages, err := h.OCR.RasterPDF(ctx, pdfBytes)
	if err != nil {
		return detectResp{
			Source:  "none",
			Message: "Failed to rasterize PDF for vision-AI: " + err.Error(),
		}
	}
	if len(pages) == 0 {
		return detectResp{
			Source:  "none",
			Message: "PDF rasterization produced no pages.",
		}
	}
	visFields, err := visionllm.Detect(ctx, h.AI, pages)
	if err != nil {
		return detectResp{
			Source:  "none",
			Message: "Vision-AI detection failed: " + err.Error(),
		}
	}
	props := proposalsFromHeuristic(visFields, h.OCR.DPI, idxOffset)
	// Stamp the vision source so the modal can render a different
	// confidence badge — the heuristic tier emits "heuristic", and
	// proposalsFromHeuristic doesn't know which tier called it.
	for i := range props {
		props[i].Source = "vision"
	}
	resp := detectResp{Source: "vision", Count: len(props), Proposals: props}
	if len(props) == 0 {
		resp.Source = "none"
		resp.Message = "Vision-AI couldn't find fillable fields on this document. The page may be blank, image-only without form regions, or the vision model may not support form-detection prompts well."
	}
	return resp
}

// acroformProposals runs the AcroForm extraction tier and returns
// the proposals it produced (or empty + error). Factored out so the
// cascade orchestrator in DetectFields stays readable.
func (h *Handler) acroformProposals(pdfBytes []byte) ([]Proposal, error) {
	fields, err := acroform.Extract(pdfBytes)
	if err != nil {
		// Extract is best-effort; corrupted /AcroForm dicts return
		// an error but the cascade may still succeed via heuristic.
		return nil, err
	}
	proposals := make([]Proposal, 0, len(fields))
	seenKeys := map[string]int{} // dedupe data keys across radio groups etc.
	for _, f := range fields {
		// Skip fields with no rect — nothing to render in the designer
		// overlay. List-only fields (rare) would require the user to
		// drag a box anyway, so they're not useful as proposals.
		if f.Rect == nil {
			continue
		}
		// Skip read-only fields — they'd clutter the list since the
		// runner can't fill them anyway. Author can add by hand.
		if f.ReadOnly {
			continue
		}

		widgetType := mapAcroTypeToWidget(f.Type, f.Multiline)
		if widgetType == "" {
			continue
		}

		dataKey := safeDataKey(f.Name)
		if dataKey == "" {
			continue
		}
		// Deduplicate radio-button groups: AcroForm exposes one entry
		// per button widget but they all share the parent /T name.
		// The renderer's bucketing handles "which radio is checked"
		// at fill time.
		if n := seenKeys[dataKey]; n > 0 {
			continue
		}
		seenKeys[dataKey] = 1

		p := Proposal{
			Type:       widgetType,
			Page:       maxInt(f.Page, 1),
			X:          f.Rect.X,
			Y:          f.Rect.Y,
			W:          f.Rect.W,
			H:          f.Rect.H,
			DataKey:    dataKey,
			Label:      f.Name,
			Source:     "acroform",
			Confidence: 1.0,
			Props:      defaultPropsFor(widgetType, f),
		}
		if f.PageSize != nil {
			p.PageW = f.PageSize.W
			p.PageH = f.PageSize.H
		}
		proposals = append(proposals, p)
	}
	// Polish: re-slug the per-widget /T names into snake_case and
	// disambiguate any cross-page collisions. AcroForm /T names are
	// authored, but authoring quality varies wildly — Word's PDF
	// export emits "Text1", "Text2"; LibreOffice keeps the field-
	// label-with-spaces verbatim; legacy Adobe forms use camelCase.
	// Running them through the same polish as the heuristic + vision
	// tiers gives the integrator one consistent key shape regardless
	// of how the source PDF was authored.
	return polishProposals(proposals), nil
}

// mapAcroTypeToWidget translates the acroform.Field.Type string
// (which may be the raw /FT name "Tx"/"Btn"/"Ch"/"Sig" or the
// pdfcpu-normalised "textfield"/"checkbox"/etc.) into the static
// designer's widget type vocabulary. Empty return = unsupported,
// caller skips the proposal.
func mapAcroTypeToWidget(acroType string, multiline bool) string {
	t := strings.ToLower(strings.TrimSpace(acroType))
	switch {
	case t == "tx", strings.Contains(t, "text"):
		if multiline {
			return "multiline"
		}
		return "text"
	case strings.Contains(t, "date"):
		return "date"
	case strings.Contains(t, "check"):
		return "checkbox"
	case strings.Contains(t, "radio"):
		return "radio"
	case t == "ch", strings.Contains(t, "combo"), strings.Contains(t, "drop"), strings.Contains(t, "list"):
		return "dropdown"
	case t == "btn", strings.Contains(t, "button"):
		return "button"
	case t == "sig", strings.Contains(t, "sign"):
		return "signature-field"
	}
	// Default: treat unknown as text. Better to give the author a box
	// to refine than to drop the field entirely.
	return "text"
}

// defaultPropsFor seeds sensible widget props per type so accepted
// proposals look reasonable on the canvas without the user having to
// open every Properties panel. Mirrors the inputs CreateFormTemplate
// uses when building widgets for the form-builder PDF.
func defaultPropsFor(widgetType string, f acroform.Field) map[string]interface{} {
	props := map[string]interface{}{
		"fontSize":   12,
		"fontFamily": "Helvetica",
		"color":      "#111827",
		"align":      "L",
	}
	switch widgetType {
	case "multiline":
		props["wrap"] = true
	case "checkbox", "radio":
		// Strip text styling that doesn't apply to glyph widgets.
		delete(props, "fontSize")
		delete(props, "fontFamily")
		delete(props, "color")
		delete(props, "align")
	case "dropdown":
		if len(f.Options) > 0 {
			props["options"] = f.Options
		}
	}
	if f.MaxLen > 0 {
		props["maxLength"] = f.MaxLen
	}
	if f.Tooltip != "" {
		props["tooltip"] = f.Tooltip
	}
	return props
}

// safeDataKey normalises an AcroForm field name into something
// usable as a JSON key in the integrator's `data` payload. Spaces
// → underscores, strips characters that would need quoting in most
// dot-notation paths. Keeps unicode letters/digits so non-English
// field names still work.
//
// We don't lowercase — many existing AcroForm field names are
// camelCase or PascalCase and the user expects to send the same
// shape. They can rename in the proposal-review modal if needed.
var unsafeDataKeyChars = regexp.MustCompile(`[^\p{L}\p{N}_.\-]+`)

func safeDataKey(name string) string {
	trimmed := strings.TrimSpace(name)
	if trimmed == "" {
		return ""
	}
	cleaned := unsafeDataKeyChars.ReplaceAllString(trimmed, "_")
	cleaned = strings.Trim(cleaned, "_.-")
	return cleaned
}

func looksLikePDF(mime, storageKey string) bool {
	if strings.Contains(strings.ToLower(mime), "pdf") {
		return true
	}
	return strings.HasSuffix(strings.ToLower(storageKey), ".pdf")
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func writeJSON(w http.ResponseWriter, code int, v interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(v)
}

func writeErr(w http.ResponseWriter, code int, slug, msg string) {
	writeJSON(w, code, map[string]any{"error": map[string]string{"code": slug, "message": msg}})
}
